# Basic stuff
FROM bitnami/minideb:bookworm
MAINTAINER franco.jose@qst.go.jp

# Install git
RUN apt update
RUN apt install -y git

# Clone the LIPAc EPICS distribution
WORKDIR /work
RUN git clone --recursive https://github.com/IFMIF/epics-7.0.git
WORKDIR /work/epics-7.0
RUN ./install_dependencies_debian12.sh

# Compile EPICS
RUN mkdir -p /opt/epics-7.0
RUN make build EPICS_TARGET=/opt/epics-7.0

# Delete the temporary work files
WORKDIR /
RUN rm -rf /work
